### PR TITLE
changelog: fix Kubernetes 1.19 removal date

### PR DESCRIPTION
**Pull request by amarkevich**
See #2704

### CODE REVIEW

**Comment by amarkevich** [comment]
> labels
docs

**Comment by miwithro** [comment]
already fixed.  Closing.

**Comment by amarkevich** [comment]
@miwithro similar but not the same:  CHANGELOG.md still contains the wrong date

**Comment by miwithro** [comment]
https://github.com/Azure/AKS/releases/tag/2022-01-13

**Comment by amarkevich** [comment]
> https://github.com/Azure/AKS/releases/tag/2022-01-13

This fix for https://github.com/Azure/AKS/blob/master/CHANGELOG.md

**Comment by amarkevich** [comment]
@miwithro please check the changes proposed in this PR

**Pull request closed without merging**
