### PR TITLE
Clean up readme, update, links, bug guidance, a unicorn

### PR DESCRIPTION
**Pull request by jnoller**
Sup in this PR 🍰

### CODE REVIEW

**Comment by jnoller** [comment]
@palma21 which link o-O

**Comment by palma21** [comment]
A blue create incident button pointing to a link similar to:

https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview

I can show you an example if you want once I land

**Comment by jnoller** [comment]
Yeah, drop me a screenshot, you steely eyed missile PM*! 

* The term steely-eyed missile man is a complementary term rooted in NASA's Apollo history when flight controller John Aaron's quick thinking saved the Apollo 12 mission from disaster. It refers to an engineer or astronaut who quickly devises an ingenious solution to a tough problem while under extreme pressure.

**Comment by palma21** [comment]
I will do you one better, paste this in

<a href="https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview" target="_blank"></a>



Also, good to know! :D

**Pull request merged**
